# Development Dockerfile

# Base image
ARG RUBY_VERSION=3.2.2
FROM ruby:$RUBY_VERSION-slim

# Rails app lives here
WORKDIR /rails

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn \
    postgresql-client \
    vim \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the main application
COPY . .

# Expose port 3000 for the Rails server
EXPOSE 3000

# Start the Rails server for development
CMD ["rails", "server", "-b", "0.0.0.0"]
