default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: mtg_favorites_development

test:
  <<: *default
  database: mtg_favorites_test

production:
  <<: *default
  database: mtg_favorites_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
